In [1]:
import tensorflow as tf

C:\Users\SAMEER\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a =tf.constant([2])
b =tf.constant([3])

In [3]:
c = tf.add(a, b)

In [4]:
c

<tf.Tensor 'Add:0' shape=(1,) dtype=int32>

In [5]:
sess = tf.Session()

In [6]:
print(sess.run(c))

[5]


In [7]:
d = tf.constant(2.0, tf.float32)
e = tf.constant(3.0)
f = d*e
print(sess.run(f))

6.0


In [8]:
sess.close()

In [9]:
# to avoid opening and closing of session
with tf.Session() as sess:
    res = sess.run(f)
    print(res)

6.0


In [10]:
a = tf.constant(2.5, tf.float32)
b = tf.constant(5.0)

In [11]:
m = b/a

In [12]:
with tf.Session() as sess:
    result = sess.run(m)
    print(result)

2.0


In [13]:
mat_1 = tf.constant([[1, 2],[3, 4]])
mat_2 = tf.constant([[2, 3],[1, 4]])

In [14]:
resa = tf.matmul(mat_1,mat_2)

In [15]:
with tf.Session() as sess:
    print(sess.run(resa))

[[ 4 11]
 [10 25]]


In [16]:
#to know about the type of variable
type(mat_1)

tensorflow.python.framework.ops.Tensor

In [17]:
mat_1

<tf.Tensor 'Const_6:0' shape=(2, 2) dtype=int32>

In [18]:
fill_mat = tf.fill((4, 4), 10) #create the 4x4 matrix fill with 10
with tf.Session() as sess:
    print(sess.run(fill_mat))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [19]:
my_zero = tf.zeros((4, 4))

In [20]:
with tf.Session() as sess:
    print(sess.run(my_zero))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
#we also create the Intractive sessions.so, we cannot do regular creation of session
sess= tf.InteractiveSession()

In [22]:
my_one = tf.ones((4, 4))

In [23]:
sess.run(my_one)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [24]:
m = tf.constant([[2,3,5],
                [5,4,6 ],
                [2, 2, 2]])

In [25]:
m

<tf.Tensor 'Const_8:0' shape=(3, 3) dtype=int32>

In [26]:
n = tf.ones((3, 3), tf.int32)

In [27]:
n

<tf.Tensor 'ones_1:0' shape=(3, 3) dtype=int32>

In [28]:
res = tf.matmul(m,n)

In [29]:
sess.run(tf.matmul(m, n))

array([[10, 10, 10],
       [15, 15, 15],
       [ 6,  6,  6]])

In [30]:
l = tf.random_normal((2,2))

In [31]:
k = tf.random_uniform((3,3))

In [32]:
sess.run(l)

array([[ 0.5293934 , -0.8063011 ],
       [ 1.889188  ,  0.08456615]], dtype=float32)

In [33]:
sess.run(k)

array([[0.73745203, 0.70491934, 0.11811638],
       [0.13708067, 0.98472846, 0.00311792],
       [0.8808414 , 0.32816017, 0.36183333]], dtype=float32)

In [34]:
ten = tf.random_uniform((5,5), 10, 100)

In [35]:
sess.run(ten)

array([[97.68019 , 79.94243 , 54.672665, 94.89823 , 65.118835],
       [40.59455 , 49.592453, 98.8609  , 74.624146, 37.451786],
       [10.864122, 80.7115  , 49.355057, 34.874626, 82.19179 ],
       [15.673773, 23.89453 , 10.061015, 28.886753, 35.5028  ],
       [64.79324 , 64.42528 , 83.94301 , 97.81601 , 74.46386 ]],
      dtype=float32)